# Generated by Django 2.2.6 on 2019-10-02 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='research/img')),
                ('document', models.FileField(blank=True, upload_to='research/1/')),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('slug', models.SlugField(help_text='Only change this if you know what you are doing', unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('related_projects', models.ManyToManyField(blank=True, related_name='_project_related_projects_+', to='research.Project')),
            ],
        ),
    ]
