# Generated by Django 2.2.6 on 2019-10-02 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='investigation/1/audio')),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Audio Evidence',
            },
        ),
        migrations.CreateModel(
            name='GuestInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='investigation/1/image')),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Image Evidence',
            },
        ),
        migrations.CreateModel(
            name='MiscEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, upload_to='investigation/1/misc')),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Misc Evidence',
            },
        ),
        migrations.CreateModel(
            name='PersonalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, upload_to='investigation/1/text')),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Personal Experiences',
            },
        ),
        migrations.CreateModel(
            name='VideoEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='investigation/1/video')),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Video Evidence',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(default='SPOR-00000', max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('thumbnail', models.ImageField(blank=True, upload_to='investigations/img')),
                ('date_occured', models.DateTimeField(blank=True, null=True)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('evidence_repository', models.URLField(blank=True, null=True)),
                ('conclusion', models.CharField(choices=[('indeterminate', 'Indeterminate'), ('in_progress', 'In-Progress'), ('no_activity', 'No Activity'), ('inconclusive', 'Inconclusive'), ('active', 'Active'), ('haunted', 'Haunted'), ('under_review', 'Under Review')], default='indeterminate', max_length=25)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('planning', 'Planning'), ('scheduled', 'Scheduled'), ('in_progress', 'In-Progress'), ('analysis', 'Analysis'), ('debrief', 'Debrief'), ('completed', 'Completed'), ('review', 'Review'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete')], default='proposed', max_length=25)),
                ('public', models.BooleanField(default=False)),
                ('slug', models.SlugField(help_text='Only change this if you know what you are doing', unique=True)),
                ('audio_evidence', models.ManyToManyField(blank=True, to='investigations.AudioEvidence')),
                ('case_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('image_evidence', models.ManyToManyField(blank=True, to='investigations.ImageEvidence')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Contact')),
                ('misc_evidence', models.ManyToManyField(blank=True, to='investigations.MiscEvidence')),
                ('personal_experiences', models.ManyToManyField(blank=True, to='investigations.PersonalExperience')),
                ('present_guests', models.ManyToManyField(blank=True, to='investigations.GuestInvestigator')),
                ('present_team_members', models.ManyToManyField(blank=True, to='home.TeamMember')),
                ('related_cases', models.ManyToManyField(blank=True, related_name='_case_related_cases_+', to='investigations.Case')),
                ('video_evidence', models.ManyToManyField(blank=True, to='investigations.VideoEvidence')),
            ],
        ),
    ]
